/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scheduler_Util */

#ifndef _Included_org_scheduler_Util
#define _Included_org_scheduler_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scheduler_Util
 * Method:    convertHeicBytesToJpegBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_scheduler_Util_convertHeicBytesToJpegBytes
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
